--- #YAML:1.0
name:               Music-AtonalUtil
version:            0.70
abstract:           atonal music analysis and composition
author:
    - Jeremy Mates <jmates@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::Permute:  0
    Carp:                0
    List::MoreUtils:     0
    Scalar::Util:        0
    Test::More:          0
resources:
    homepage:    http://github.com/thrig/Music-AtonalUtil
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/thrig/Music-AtonalUtil
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
